# Generated by Django 2.0 on 2018-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20181010_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='review',
            field=models.CharField(max_length=50),
        ),
    ]
